name: business_assets
description: "Assets management app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  equatable: ^2.0.5
  auto_injector: ^2.0.5
  dio: ^5.7.0
  flutter_svg: ^2.0.14
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
