// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:flutter/material.dart';

import '../../config/application.dart';
import '../../domain/commom/uid.dart';
import '../../domain/company_asset/company_asset_repository.dart';
import '../../domain/company_location/company_location_repository.dart';
import '../models/asset_tree_node.dart';
import '../widgets/asset_tree.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with ServiceLocatorMixin {
  late final assetRepository = instance<CompanyAssetRepository>();
  late final locationRepository = instance<CompanyLocationRepository>();

  List<TreeNodeModel> _nodes = [];

  void _loadAssets() async {
    final companyId = Uid.fromString('662fd0fab3fd5656edb39af5');
    final assets = await assetRepository.fromCompany(companyId);
    final locations = await locationRepository.fromCompany(companyId);
    final assetNodes = assets.map(TreeNodeModel.fromCompanyAsset);
    final locationNodes = locations.map(TreeNodeModel.fromCompanyLocation);
    setState(() {
      _nodes = [...assetNodes, ...locationNodes];
    });
  }

  @override
  void initState() {
    super.initState();
    _loadAssets();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Assets'),
        centerTitle: true,
      ),
      body: _nodes.isEmpty
          ? Center(child: CircularProgressIndicator())
          : AssetTree(nodes: _nodes),
    );
  }
}
