// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:flutter/material.dart';

import '../../config/application.dart';
import '../../domain/commom/uid.dart';
import '../../domain/company_asset/company_asset_repository.dart';
import '../../domain/company_location/company_location_repository.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with ServiceLocatorMixin {
  late final assetRepository = instance<CompanyAssetRepository>();
  late final locationRepository = instance<CompanyLocationRepository>();

  Map<Uid, List<TreeNode>> _treeNodes = {};

  final rootId = Uid.fromString('root');

  void _loadAssets() async {
    final companyId = Uid.fromString('662fd0ee639069143a8fc387');
    final assets = await assetRepository.fromCompany(companyId);
    final locations = await locationRepository.fromCompany(companyId);

    final assetNodes = assets.map((asset) {
      return TreeNode(
        id: asset.id,
        name: asset.name,
        parentId: asset.parentId ?? asset.locationId,
      );
    });

    final locationNodes = locations.map((location) {
      return TreeNode(
        id: location.id,
        name: location.name,
        parentId: location.parentId,
      );
    });

    final nodes = [...assetNodes, ...locationNodes];

    for (final node in nodes) {
      final parentId = node.parentId ?? rootId;
      if (!_treeNodes.containsKey(parentId)) {
        _treeNodes[parentId] = [];
      }
      _treeNodes[parentId]?.add(node);
    }

    debugPrint('${_treeNodes}', wrapWidth: 1024);
  }

  @override
  void initState() {
    super.initState();
    _loadAssets();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Assets'),
        centerTitle: true,
      ),
      body: Container(),
    );
  }
}

class TreeNode {
  final Uid id;
  final Uid? parentId;
  final String name;

  TreeNode({
    required this.id,
    required this.name,
    this.parentId,
  });

  @override
  String toString() => 'TreeNode(id: $id, name: $name)';
}
