// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:equatable/equatable.dart';

import '../../../../../core/domain/commom/company_resource.dart';

class AssetsTreeNodeModel extends Equatable {
  final CompanyResource resource;

  const AssetsTreeNodeModel({
    required this.resource,
    this.level = 0,
    this.expanded = false,
  });

  final int level;
  final bool expanded;

  @override
  final stringify = true;

  @override
  List<Object?> get props => [level, expanded, resource];

  AssetsTreeNodeModel copyWith({
    CompanyResource? resource,
    int? level,
    bool? expanded,
  }) {
    return AssetsTreeNodeModel(
      resource: resource ?? this.resource,
      level: level ?? this.level,
      expanded: expanded ?? this.expanded,
    );
  }
}
